### ISSUE TITLE
CMake version issues

### ISSUE THREAD

**Issue by rupertnash** [MxUI/MUI-demo#7]
The hello world demo CMakeLists.txt uses the `DESCRIPTION` optional single value argument to `project`, which requires `cmake_minimum_required(VERSION 3.9)` instead of 3.1.

I suggest you either remove the `DESCRIPTION` option or correct the min required version as project taste prefers.

**Comment by rupertnash** [comment]
Given that there is no FindMUI.cmake here or in the main MUI repo, I suggest you instead just revert to the makefile until MUI provides the CMake necessary.

**Comment by AlexSkillen** [comment]
Thanks for the bug report. I need to merge the dev branch of MUI to master. The findMUI.cmake is on that branch. And indeed, it should be version 3.9.

**Comment by SLongshaw** [comment]
This issue is now fairly old and the dev branch has been merged into the master since it was created. While it may not be completely resolved, the original Makefile structure is in place for all demos with CMake examples provided but not the default nor required.

I'm going to close this for now with the promise that ongoing developments to the library to introduce new functionality will likely result in the need to focus on ensuring a proper build system is in place (most likely CMake), so making sure the demos are properly considered will be part of this process.
